# Generated by Django 6.1.1 on 2026-09-24 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tags', to='posts.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post', 'name'), name='unique_post_skill_tag')],
            },
        ),
    ]
