# Generated by Django 6.1.1 on 2026-09-16 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('logo', models.CharField(default='💼', max_length=255)),
                ('type', models.CharField(choices=[('دوام كامل', 'دوام كامل'), ('دوام جزئي', 'دوام جزئي'), ('عن بُعد', 'عن بُعد'), ('عمل حر', 'عمل حر'), ('تدريب', 'تدريب')], default='دوام كامل', max_length=50)),
                ('domain', models.CharField(default='تطوير البرمجيات', max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('posted_time', models.CharField(default='الآن', max_length=100)),
                ('applicants_count', models.IntegerField(default=0)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('logo', models.CharField(default='💼', max_length=255)),
                ('apply_date', models.CharField(default='اليوم', max_length=100)),
                ('status', models.CharField(choices=[('التقدم', 'التقدم'), ('المراجعة', 'المراجعة'), ('الاختصار', 'الاختصار'), ('المقابلة', 'المقابلة'), ('العرض', 'العرض'), ('التوظيف', 'التوظيف'), ('مرفوض', 'مرفوض')], default='التقدم', max_length=50)),
                ('current_step_index', models.IntegerField(default=0)),
                ('interview_date', models.CharField(blank=True, max_length=150, null=True)),
                ('interview_note', models.TextField(blank=True, null=True)),
                ('resume_file_name', models.CharField(default='السيرة الذاتية.pdf', max_length=255)),
                ('cover_note', models.TextField(blank=True, null=True)),
                ('candidate_name', models.CharField(blank=True, max_length=255)),
                ('candidate_headline', models.TextField(blank=True)),
                ('candidate_avatar', models.CharField(default='أر', max_length=255)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('candidate_phone', models.CharField(blank=True, max_length=50)),
                ('experience_years', models.IntegerField(default=3)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('match_score', models.IntegerField(default=85)),
                ('candidate_skills', models.JSONField(blank=True, default=list)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
