# Generated by Django 6.1.1 on 2026-09-16 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.CharField(default='💼', max_length=255)),
                ('last_message', models.TextField(blank=True)),
                ('last_message_time', models.CharField(default='الآن', max_length=100)),
                ('unread_count', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('shared_files', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'user'), ('company', 'company')], default='company', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('time', models.CharField(default='الآن', max_length=100)),
                ('is_offer', models.BooleanField(default=False)),
                ('offer_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
        ),
    ]
