# Generated by Django 6.1.1 on 2026-09-16 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.CharField(default='🏢', max_length=255)),
                ('cover_gradient', models.CharField(default='from-blue-600 to-indigo-700', max_length=255)),
                ('industry', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('employees_count', models.CharField(default='50-200 موظف', max_length=100)),
                ('founded_year', models.CharField(default='2020', max_length=50)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(default=4.8)),
                ('reviews_count', models.IntegerField(default=10)),
                ('is_verified', models.BooleanField(default=True)),
                ('open_jobs_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
